[package]
name = "howmanysmall/matter2"
version = "0.1.2-fix"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["example", "docs", "Packages", ".moonwave", "build", "pages", "tests"]

[dependencies]
